"""
Sentinel-2 Land Cover Classifier

Trains a Random Forest on multispectral pixel features derived from
Sentinel-2 bands (or the synthetic equivalent generated by download_data.py).

Key spectral indices computed:
  NDVI  = (NIR - Red) / (NIR + Red)          — vegetation health
  NDWI  = (Green - NIR) / (Green + NIR)       — water bodies
  NDBI  = (SWIR - NIR) / (SWIR + NIR)         — built-up / urban
  EVI   = 2.5 * (NIR - Red) / (NIR + 6*Red - 7.5*Blue + 1)
"""

import numpy as np
import os
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
import joblib

# Band indices for Sentinel-2 12-band layout (0-indexed)
BLUE   = 0   # B2  ~490nm
GREEN  = 1   # B3  ~560nm
RED    = 2   # B4  ~665nm
RE1    = 3   # B5  ~705nm  Red Edge
RE2    = 4   # B6  ~740nm  Red Edge
RE3    = 5   # B7  ~783nm  Red Edge
NIR    = 6   # B8  ~842nm  Near Infrared
NIR_N  = 7   # B8A ~865nm  Narrow NIR
SWIR1  = 10  # B11 ~1610nm Short-Wave Infrared
SWIR2  = 11  # B12 ~2190nm Short-Wave Infrared

CLASS_NAMES = {0: "Water", 1: "Forest", 2: "Urban", 3: "Agriculture", 4: "Bare Soil"}

MODEL_PATH = "models/rf_land_cover.joblib"
SCALER_PATH = "models/scaler.joblib"


def safe_ratio(a, b, eps=1e-8):
    """Prevents division by zero in spectral index calculations."""
    return (a - b) / (a + b + eps)


def compute_spectral_indices(image: np.ndarray) -> np.ndarray:
    """
    Appends spectral indices to raw band values.
    Input: (H, W, n_bands)
    Output: (H, W, n_bands + 4)  — four indices appended
    """
    B = image[:, :, BLUE]
    G = image[:, :, GREEN]
    R = image[:, :, RED]
    N = image[:, :, NIR]
    S1 = image[:, :, SWIR1]

    ndvi = safe_ratio(N, R)
    ndwi = safe_ratio(G, N)
    ndbi = safe_ratio(S1, N)
    evi  = 2.5 * (N - R) / (N + 6 * R - 7.5 * B + 1 + 1e-8)

    indices = np.stack([ndvi, ndwi, ndbi, evi], axis=-1)
    return np.concatenate([image, indices], axis=-1)


def flatten_pixels(image: np.ndarray, labels: np.ndarray):
    """
    Reshapes image from (H, W, C) → (N_pixels, C) and labels to (N_pixels,).
    Used to convert the spatial image into a tabular feature matrix for sklearn.
    """
    H, W, C = image.shape
    X = image.reshape(-1, C)
    y = labels.reshape(-1)
    return X, y


def train(data_dir="data/synthetic", model_dir="models"):
    os.makedirs(model_dir, exist_ok=True)

    print("Loading data...")
    image  = np.load(os.path.join(data_dir, "image.npy"))
    labels = np.load(os.path.join(data_dir, "labels.npy"))

    print("Computing spectral indices...")
    image_feat = compute_spectral_indices(image)

    X, y = flatten_pixels(image_feat, labels)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test  = scaler.transform(X_test)

    print("Training Random Forest (100 trees)...")
    clf = RandomForestClassifier(
        n_estimators=100,
        max_depth=None,
        min_samples_leaf=5,
        n_jobs=-1,
        random_state=42,
    )
    clf.fit(X_train, y_train)

    y_pred = clf.predict(X_test)
    print("\n=== Classification Report ===")
    print(classification_report(y_test, y_pred, target_names=list(CLASS_NAMES.values())))

    joblib.dump(clf, MODEL_PATH)
    joblib.dump(scaler, SCALER_PATH)
    print(f"\nModel saved to {MODEL_PATH}")

    return clf, scaler, image_feat, labels


def predict_map(image: np.ndarray, clf, scaler) -> np.ndarray:
    """
    Runs inference over a full image and returns a 2D land cover map.
    """
    image_feat = compute_spectral_indices(image)
    H, W, C = image_feat.shape
    X = image_feat.reshape(-1, C)
    X_scaled = scaler.transform(X)
    pred = clf.predict(X_scaled)
    return pred.reshape(H, W)


def load_model():
    clf    = joblib.load(MODEL_PATH)
    scaler = joblib.load(SCALER_PATH)
    return clf, scaler


if __name__ == "__main__":
    train()
